FROM node:24-alpine AS build-stage
WORKDIR /app

ARG BUILD_MODE=production
ENV NODE_ENV_BUILD=development
ENV NODE_ENV=$BUILD_MODE

COPY package.json ./package.json
COPY package-lock.json ./package-lock.json
RUN npm ci  --include=dev
COPY . .
# надо устанавливать дважды и не задавать лишних вопросов
RUN if [ "$BUILD_MODE" = "devbuild" ]; then npm run build:dev; else npm run build; fi

FROM node:22.18.0-alpine AS production-stage
WORKDIR /app
COPY --from=build-stage /app/dist /app/dist
RUN npm install -g serve
EXPOSE 80
CMD ["serve", "-s", "dist", "-l", "80"]
