// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.1
// source: messages.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CellType int32

const (
	CellType_CELL_TYPE_NEIGHBOR_0 CellType = 0   // Открытая клетка с 0 соседних мин
	CellType_CELL_TYPE_NEIGHBOR_1 CellType = 1   // Открытая клетка с 1 соседней миной
	CellType_CELL_TYPE_NEIGHBOR_2 CellType = 2   // Открытая клетка с 2 соседними минами
	CellType_CELL_TYPE_NEIGHBOR_3 CellType = 3   // Открытая клетка с 3 соседними минами
	CellType_CELL_TYPE_NEIGHBOR_4 CellType = 4   // Открытая клетка с 4 соседними минами
	CellType_CELL_TYPE_NEIGHBOR_5 CellType = 5   // Открытая клетка с 5 соседними минами
	CellType_CELL_TYPE_NEIGHBOR_6 CellType = 6   // Открытая клетка с 6 соседними минами
	CellType_CELL_TYPE_NEIGHBOR_7 CellType = 7   // Открытая клетка с 7 соседними минами
	CellType_CELL_TYPE_NEIGHBOR_8 CellType = 8   // Открытая клетка с 8 соседними минами
	CellType_CELL_TYPE_MINE       CellType = 9   // Мина
	CellType_CELL_TYPE_SAFE       CellType = 10  // Зеленая (SAFE) - для режима обучения (закрытая)
	CellType_CELL_TYPE_UNKNOWN    CellType = 11  // Желтая (UNKNOWN) - для режима обучения (закрытая)
	CellType_CELL_TYPE_DANGER     CellType = 12  // Красная (MINE) - для режима обучения (закрытая)
	CellType_CELL_TYPE_CLOSED     CellType = 255 // Закрыта (без подсказок)
)

// Enum value maps for CellType.
var (
	CellType_name = map[int32]string{
		0:   "CELL_TYPE_NEIGHBOR_0",
		1:   "CELL_TYPE_NEIGHBOR_1",
		2:   "CELL_TYPE_NEIGHBOR_2",
		3:   "CELL_TYPE_NEIGHBOR_3",
		4:   "CELL_TYPE_NEIGHBOR_4",
		5:   "CELL_TYPE_NEIGHBOR_5",
		6:   "CELL_TYPE_NEIGHBOR_6",
		7:   "CELL_TYPE_NEIGHBOR_7",
		8:   "CELL_TYPE_NEIGHBOR_8",
		9:   "CELL_TYPE_MINE",
		10:  "CELL_TYPE_SAFE",
		11:  "CELL_TYPE_UNKNOWN",
		12:  "CELL_TYPE_DANGER",
		255: "CELL_TYPE_CLOSED",
	}
	CellType_value = map[string]int32{
		"CELL_TYPE_NEIGHBOR_0": 0,
		"CELL_TYPE_NEIGHBOR_1": 1,
		"CELL_TYPE_NEIGHBOR_2": 2,
		"CELL_TYPE_NEIGHBOR_3": 3,
		"CELL_TYPE_NEIGHBOR_4": 4,
		"CELL_TYPE_NEIGHBOR_5": 5,
		"CELL_TYPE_NEIGHBOR_6": 6,
		"CELL_TYPE_NEIGHBOR_7": 7,
		"CELL_TYPE_NEIGHBOR_8": 8,
		"CELL_TYPE_MINE":       9,
		"CELL_TYPE_SAFE":       10,
		"CELL_TYPE_UNKNOWN":    11,
		"CELL_TYPE_DANGER":     12,
		"CELL_TYPE_CLOSED":     255,
	}
)

func (x CellType) Enum() *CellType {
	p := new(CellType)
	*p = x
	return p
}

func (x CellType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CellType) Descriptor() protoreflect.EnumDescriptor {
	return file_messages_proto_enumTypes[0].Descriptor()
}

func (CellType) Type() protoreflect.EnumType {
	return &file_messages_proto_enumTypes[0]
}

func (x CellType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CellType.Descriptor instead.
func (CellType) EnumDescriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

// Основное сообщение WebSocket
type WebSocketMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*WebSocketMessage_GameState
	//	*WebSocketMessage_Chat
	//	*WebSocketMessage_Cursor
	//	*WebSocketMessage_Players
	//	*WebSocketMessage_Pong
	//	*WebSocketMessage_Error
	//	*WebSocketMessage_CellUpdate
	Message       isWebSocketMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebSocketMessage) Reset() {
	*x = WebSocketMessage{}
	mi := &file_messages_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebSocketMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebSocketMessage) ProtoMessage() {}

func (x *WebSocketMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebSocketMessage.ProtoReflect.Descriptor instead.
func (*WebSocketMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{0}
}

func (x *WebSocketMessage) GetMessage() isWebSocketMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *WebSocketMessage) GetGameState() *GameStateMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_GameState); ok {
			return x.GameState
		}
	}
	return nil
}

func (x *WebSocketMessage) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *WebSocketMessage) GetCursor() *CursorMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_Cursor); ok {
			return x.Cursor
		}
	}
	return nil
}

func (x *WebSocketMessage) GetPlayers() *PlayersMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_Players); ok {
			return x.Players
		}
	}
	return nil
}

func (x *WebSocketMessage) GetPong() *PongMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_Pong); ok {
			return x.Pong
		}
	}
	return nil
}

func (x *WebSocketMessage) GetError() *ErrorMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *WebSocketMessage) GetCellUpdate() *CellUpdateMessage {
	if x != nil {
		if x, ok := x.Message.(*WebSocketMessage_CellUpdate); ok {
			return x.CellUpdate
		}
	}
	return nil
}

type isWebSocketMessage_Message interface {
	isWebSocketMessage_Message()
}

type WebSocketMessage_GameState struct {
	GameState *GameStateMessage `protobuf:"bytes,1,opt,name=game_state,json=gameState,proto3,oneof"`
}

type WebSocketMessage_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,2,opt,name=chat,proto3,oneof"`
}

type WebSocketMessage_Cursor struct {
	Cursor *CursorMessage `protobuf:"bytes,3,opt,name=cursor,proto3,oneof"`
}

type WebSocketMessage_Players struct {
	Players *PlayersMessage `protobuf:"bytes,4,opt,name=players,proto3,oneof"`
}

type WebSocketMessage_Pong struct {
	Pong *PongMessage `protobuf:"bytes,5,opt,name=pong,proto3,oneof"`
}

type WebSocketMessage_Error struct {
	Error *ErrorMessage `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type WebSocketMessage_CellUpdate struct {
	CellUpdate *CellUpdateMessage `protobuf:"bytes,7,opt,name=cell_update,json=cellUpdate,proto3,oneof"`
}

func (*WebSocketMessage_GameState) isWebSocketMessage_Message() {}

func (*WebSocketMessage_Chat) isWebSocketMessage_Message() {}

func (*WebSocketMessage_Cursor) isWebSocketMessage_Message() {}

func (*WebSocketMessage_Players) isWebSocketMessage_Message() {}

func (*WebSocketMessage_Pong) isWebSocketMessage_Message() {}

func (*WebSocketMessage_Error) isWebSocketMessage_Message() {}

func (*WebSocketMessage_CellUpdate) isWebSocketMessage_Message() {}

// Входящее сообщение от клиента
type ClientMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*ClientMessage_Nickname
	//	*ClientMessage_Cursor
	//	*ClientMessage_CellClick
	//	*ClientMessage_Hint
	//	*ClientMessage_NewGame
	//	*ClientMessage_Chat
	//	*ClientMessage_Ping
	Message       isClientMessage_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientMessage) Reset() {
	*x = ClientMessage{}
	mi := &file_messages_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientMessage) ProtoMessage() {}

func (x *ClientMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientMessage.ProtoReflect.Descriptor instead.
func (*ClientMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{1}
}

func (x *ClientMessage) GetMessage() isClientMessage_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *ClientMessage) GetNickname() string {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Nickname); ok {
			return x.Nickname
		}
	}
	return ""
}

func (x *ClientMessage) GetCursor() *CursorMessage {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Cursor); ok {
			return x.Cursor
		}
	}
	return nil
}

func (x *ClientMessage) GetCellClick() *CellClickMessage {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_CellClick); ok {
			return x.CellClick
		}
	}
	return nil
}

func (x *ClientMessage) GetHint() *HintMessage {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Hint); ok {
			return x.Hint
		}
	}
	return nil
}

func (x *ClientMessage) GetNewGame() *NewGameMessage {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_NewGame); ok {
			return x.NewGame
		}
	}
	return nil
}

func (x *ClientMessage) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *ClientMessage) GetPing() *PingMessage {
	if x != nil {
		if x, ok := x.Message.(*ClientMessage_Ping); ok {
			return x.Ping
		}
	}
	return nil
}

type isClientMessage_Message interface {
	isClientMessage_Message()
}

type ClientMessage_Nickname struct {
	Nickname string `protobuf:"bytes,1,opt,name=nickname,proto3,oneof"`
}

type ClientMessage_Cursor struct {
	Cursor *CursorMessage `protobuf:"bytes,2,opt,name=cursor,proto3,oneof"`
}

type ClientMessage_CellClick struct {
	CellClick *CellClickMessage `protobuf:"bytes,3,opt,name=cell_click,json=cellClick,proto3,oneof"`
}

type ClientMessage_Hint struct {
	Hint *HintMessage `protobuf:"bytes,4,opt,name=hint,proto3,oneof"`
}

type ClientMessage_NewGame struct {
	NewGame *NewGameMessage `protobuf:"bytes,5,opt,name=new_game,json=newGame,proto3,oneof"`
}

type ClientMessage_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,6,opt,name=chat,proto3,oneof"`
}

type ClientMessage_Ping struct {
	Ping *PingMessage `protobuf:"bytes,7,opt,name=ping,proto3,oneof"`
}

func (*ClientMessage_Nickname) isClientMessage_Message() {}

func (*ClientMessage_Cursor) isClientMessage_Message() {}

func (*ClientMessage_CellClick) isClientMessage_Message() {}

func (*ClientMessage_Hint) isClientMessage_Message() {}

func (*ClientMessage_NewGame) isClientMessage_Message() {}

func (*ClientMessage_Chat) isClientMessage_Message() {}

func (*ClientMessage_Ping) isClientMessage_Message() {}

// Состояние игры
type GameStateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Board         *Board                 `protobuf:"bytes,1,opt,name=board,proto3" json:"board,omitempty"`
	Rows          int32                  `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols          int32                  `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	Mines         int32                  `protobuf:"varint,4,opt,name=mines,proto3" json:"mines,omitempty"`
	GameOver      bool                   `protobuf:"varint,5,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
	GameWon       bool                   `protobuf:"varint,6,opt,name=game_won,json=gameWon,proto3" json:"game_won,omitempty"`
	Revealed      int32                  `protobuf:"varint,7,opt,name=revealed,proto3" json:"revealed,omitempty"`
	HintsUsed     int32                  `protobuf:"varint,8,opt,name=hints_used,json=hintsUsed,proto3" json:"hints_used,omitempty"`
	SafeCells     []*SafeCell            `protobuf:"bytes,9,rep,name=safe_cells,json=safeCells,proto3" json:"safe_cells,omitempty"`
	CellHints     []*CellHint            `protobuf:"bytes,10,rep,name=cell_hints,json=cellHints,proto3" json:"cell_hints,omitempty"`
	LoserPlayerId string                 `protobuf:"bytes,11,opt,name=loser_player_id,json=loserPlayerId,proto3" json:"loser_player_id,omitempty"`
	LoserNickname string                 `protobuf:"bytes,12,opt,name=loser_nickname,json=loserNickname,proto3" json:"loser_nickname,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GameStateMessage) Reset() {
	*x = GameStateMessage{}
	mi := &file_messages_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GameStateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GameStateMessage) ProtoMessage() {}

func (x *GameStateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GameStateMessage.ProtoReflect.Descriptor instead.
func (*GameStateMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{2}
}

func (x *GameStateMessage) GetBoard() *Board {
	if x != nil {
		return x.Board
	}
	return nil
}

func (x *GameStateMessage) GetRows() int32 {
	if x != nil {
		return x.Rows
	}
	return 0
}

func (x *GameStateMessage) GetCols() int32 {
	if x != nil {
		return x.Cols
	}
	return 0
}

func (x *GameStateMessage) GetMines() int32 {
	if x != nil {
		return x.Mines
	}
	return 0
}

func (x *GameStateMessage) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

func (x *GameStateMessage) GetGameWon() bool {
	if x != nil {
		return x.GameWon
	}
	return false
}

func (x *GameStateMessage) GetRevealed() int32 {
	if x != nil {
		return x.Revealed
	}
	return 0
}

func (x *GameStateMessage) GetHintsUsed() int32 {
	if x != nil {
		return x.HintsUsed
	}
	return 0
}

func (x *GameStateMessage) GetSafeCells() []*SafeCell {
	if x != nil {
		return x.SafeCells
	}
	return nil
}

func (x *GameStateMessage) GetCellHints() []*CellHint {
	if x != nil {
		return x.CellHints
	}
	return nil
}

func (x *GameStateMessage) GetLoserPlayerId() string {
	if x != nil {
		return x.LoserPlayerId
	}
	return ""
}

func (x *GameStateMessage) GetLoserNickname() string {
	if x != nil {
		return x.LoserNickname
	}
	return ""
}

type Board struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rows          []*Row                 `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Board) Reset() {
	*x = Board{}
	mi := &file_messages_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Board) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Board) ProtoMessage() {}

func (x *Board) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Board.ProtoReflect.Descriptor instead.
func (*Board) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{3}
}

func (x *Board) GetRows() []*Row {
	if x != nil {
		return x.Rows
	}
	return nil
}

type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cells         []*Cell                `protobuf:"bytes,1,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_messages_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{4}
}

func (x *Row) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Cell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsMine        bool                   `protobuf:"varint,1,opt,name=is_mine,json=isMine,proto3" json:"is_mine,omitempty"`
	IsRevealed    bool                   `protobuf:"varint,2,opt,name=is_revealed,json=isRevealed,proto3" json:"is_revealed,omitempty"`
	IsFlagged     bool                   `protobuf:"varint,3,opt,name=is_flagged,json=isFlagged,proto3" json:"is_flagged,omitempty"`
	NeighborMines int32                  `protobuf:"varint,4,opt,name=neighbor_mines,json=neighborMines,proto3" json:"neighbor_mines,omitempty"`
	FlagColor     string                 `protobuf:"bytes,5,opt,name=flag_color,json=flagColor,proto3" json:"flag_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_messages_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{5}
}

func (x *Cell) GetIsMine() bool {
	if x != nil {
		return x.IsMine
	}
	return false
}

func (x *Cell) GetIsRevealed() bool {
	if x != nil {
		return x.IsRevealed
	}
	return false
}

func (x *Cell) GetIsFlagged() bool {
	if x != nil {
		return x.IsFlagged
	}
	return false
}

func (x *Cell) GetNeighborMines() int32 {
	if x != nil {
		return x.NeighborMines
	}
	return 0
}

func (x *Cell) GetFlagColor() string {
	if x != nil {
		return x.FlagColor
	}
	return ""
}

type SafeCell struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SafeCell) Reset() {
	*x = SafeCell{}
	mi := &file_messages_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeCell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeCell) ProtoMessage() {}

func (x *SafeCell) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeCell.ProtoReflect.Descriptor instead.
func (*SafeCell) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{6}
}

func (x *SafeCell) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *SafeCell) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

type CellHint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"` // "MINE", "SAFE", "UNKNOWN"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellHint) Reset() {
	*x = CellHint{}
	mi := &file_messages_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellHint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellHint) ProtoMessage() {}

func (x *CellHint) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellHint.ProtoReflect.Descriptor instead.
func (*CellHint) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{7}
}

func (x *CellHint) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *CellHint) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *CellHint) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Сообщение чата
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	IsSystem      bool                   `protobuf:"varint,5,opt,name=is_system,json=isSystem,proto3" json:"is_system,omitempty"`
	Action        string                 `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"` // "flag", "reveal", "explode"
	Row           int32                  `protobuf:"varint,7,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,8,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_messages_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{8}
}

func (x *ChatMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *ChatMessage) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *ChatMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *ChatMessage) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ChatMessage) GetIsSystem() bool {
	if x != nil {
		return x.IsSystem
	}
	return false
}

func (x *ChatMessage) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *ChatMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *ChatMessage) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

// Позиция курсора
type CursorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlayerId      string                 `protobuf:"bytes,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	X             float64                `protobuf:"fixed64,4,opt,name=x,proto3" json:"x,omitempty"`
	Y             float64                `protobuf:"fixed64,5,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CursorMessage) Reset() {
	*x = CursorMessage{}
	mi := &file_messages_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CursorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CursorMessage) ProtoMessage() {}

func (x *CursorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CursorMessage.ProtoReflect.Descriptor instead.
func (*CursorMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{9}
}

func (x *CursorMessage) GetPlayerId() string {
	if x != nil {
		return x.PlayerId
	}
	return ""
}

func (x *CursorMessage) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *CursorMessage) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *CursorMessage) GetX() float64 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CursorMessage) GetY() float64 {
	if x != nil {
		return x.Y
	}
	return 0
}

// Список игроков
type PlayersMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Players       []*Player              `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlayersMessage) Reset() {
	*x = PlayersMessage{}
	mi := &file_messages_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlayersMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlayersMessage) ProtoMessage() {}

func (x *PlayersMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlayersMessage.ProtoReflect.Descriptor instead.
func (*PlayersMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{10}
}

func (x *PlayersMessage) GetPlayers() []*Player {
	if x != nil {
		return x.Players
	}
	return nil
}

type Player struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Color         string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Player) Reset() {
	*x = Player{}
	mi := &file_messages_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Player) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Player) ProtoMessage() {}

func (x *Player) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Player.ProtoReflect.Descriptor instead.
func (*Player) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{11}
}

func (x *Player) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Player) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *Player) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

// Сообщение об ошибке
type ErrorMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorMessage) Reset() {
	*x = ErrorMessage{}
	mi := &file_messages_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorMessage) ProtoMessage() {}

func (x *ErrorMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorMessage.ProtoReflect.Descriptor instead.
func (*ErrorMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{12}
}

func (x *ErrorMessage) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Pong сообщение
type PongMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PongMessage) Reset() {
	*x = PongMessage{}
	mi := &file_messages_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PongMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PongMessage) ProtoMessage() {}

func (x *PongMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PongMessage.ProtoReflect.Descriptor instead.
func (*PongMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{13}
}

// Ping сообщение
type PingMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingMessage) Reset() {
	*x = PingMessage{}
	mi := &file_messages_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingMessage) ProtoMessage() {}

func (x *PingMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingMessage.ProtoReflect.Descriptor instead.
func (*PingMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{14}
}

// Клик по клетке
type CellClickMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Flag          bool                   `protobuf:"varint,3,opt,name=flag,proto3" json:"flag,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellClickMessage) Reset() {
	*x = CellClickMessage{}
	mi := &file_messages_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellClickMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellClickMessage) ProtoMessage() {}

func (x *CellClickMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellClickMessage.ProtoReflect.Descriptor instead.
func (*CellClickMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{15}
}

func (x *CellClickMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *CellClickMessage) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *CellClickMessage) GetFlag() bool {
	if x != nil {
		return x.Flag
	}
	return false
}

// Подсказка
type HintMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HintMessage) Reset() {
	*x = HintMessage{}
	mi := &file_messages_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HintMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HintMessage) ProtoMessage() {}

func (x *HintMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HintMessage.ProtoReflect.Descriptor instead.
func (*HintMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{16}
}

func (x *HintMessage) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *HintMessage) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

// Новая игра
type NewGameMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NewGameMessage) Reset() {
	*x = NewGameMessage{}
	mi := &file_messages_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NewGameMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewGameMessage) ProtoMessage() {}

func (x *NewGameMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewGameMessage.ProtoReflect.Descriptor instead.
func (*NewGameMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{17}
}

// Обновление клеток
type CellUpdateMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GameOver      bool                   `protobuf:"varint,1,opt,name=game_over,json=gameOver,proto3" json:"game_over,omitempty"`
	GameWon       bool                   `protobuf:"varint,2,opt,name=game_won,json=gameWon,proto3" json:"game_won,omitempty"`
	Revealed      int32                  `protobuf:"varint,3,opt,name=revealed,proto3" json:"revealed,omitempty"`
	HintsUsed     int32                  `protobuf:"varint,4,opt,name=hints_used,json=hintsUsed,proto3" json:"hints_used,omitempty"`
	LoserPlayerId string                 `protobuf:"bytes,5,opt,name=loser_player_id,json=loserPlayerId,proto3" json:"loser_player_id,omitempty"`
	LoserNickname string                 `protobuf:"bytes,6,opt,name=loser_nickname,json=loserNickname,proto3" json:"loser_nickname,omitempty"`
	Updates       []*CellUpdate          `protobuf:"bytes,7,rep,name=updates,proto3" json:"updates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellUpdateMessage) Reset() {
	*x = CellUpdateMessage{}
	mi := &file_messages_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellUpdateMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellUpdateMessage) ProtoMessage() {}

func (x *CellUpdateMessage) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellUpdateMessage.ProtoReflect.Descriptor instead.
func (*CellUpdateMessage) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{18}
}

func (x *CellUpdateMessage) GetGameOver() bool {
	if x != nil {
		return x.GameOver
	}
	return false
}

func (x *CellUpdateMessage) GetGameWon() bool {
	if x != nil {
		return x.GameWon
	}
	return false
}

func (x *CellUpdateMessage) GetRevealed() int32 {
	if x != nil {
		return x.Revealed
	}
	return 0
}

func (x *CellUpdateMessage) GetHintsUsed() int32 {
	if x != nil {
		return x.HintsUsed
	}
	return 0
}

func (x *CellUpdateMessage) GetLoserPlayerId() string {
	if x != nil {
		return x.LoserPlayerId
	}
	return ""
}

func (x *CellUpdateMessage) GetLoserNickname() string {
	if x != nil {
		return x.LoserNickname
	}
	return ""
}

func (x *CellUpdateMessage) GetUpdates() []*CellUpdate {
	if x != nil {
		return x.Updates
	}
	return nil
}

type CellUpdate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Row           int32                  `protobuf:"varint,1,opt,name=row,proto3" json:"row,omitempty"`
	Col           int32                  `protobuf:"varint,2,opt,name=col,proto3" json:"col,omitempty"`
	Type          CellType               `protobuf:"varint,3,opt,name=type,proto3,enum=messages.CellType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CellUpdate) Reset() {
	*x = CellUpdate{}
	mi := &file_messages_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CellUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CellUpdate) ProtoMessage() {}

func (x *CellUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_messages_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CellUpdate.ProtoReflect.Descriptor instead.
func (*CellUpdate) Descriptor() ([]byte, []int) {
	return file_messages_proto_rawDescGZIP(), []int{19}
}

func (x *CellUpdate) GetRow() int32 {
	if x != nil {
		return x.Row
	}
	return 0
}

func (x *CellUpdate) GetCol() int32 {
	if x != nil {
		return x.Col
	}
	return 0
}

func (x *CellUpdate) GetType() CellType {
	if x != nil {
		return x.Type
	}
	return CellType_CELL_TYPE_NEIGHBOR_0
}

var File_messages_proto protoreflect.FileDescriptor

const file_messages_proto_rawDesc = "" +
	"\n" +
	"\x0emessages.proto\x12\bmessages\"\x8d\x03\n" +
	"\x10WebSocketMessage\x12;\n" +
	"\n" +
	"game_state\x18\x01 \x01(\v2\x1a.messages.GameStateMessageH\x00R\tgameState\x12+\n" +
	"\x04chat\x18\x02 \x01(\v2\x15.messages.ChatMessageH\x00R\x04chat\x121\n" +
	"\x06cursor\x18\x03 \x01(\v2\x17.messages.CursorMessageH\x00R\x06cursor\x124\n" +
	"\aplayers\x18\x04 \x01(\v2\x18.messages.PlayersMessageH\x00R\aplayers\x12+\n" +
	"\x04pong\x18\x05 \x01(\v2\x15.messages.PongMessageH\x00R\x04pong\x12.\n" +
	"\x05error\x18\x06 \x01(\v2\x16.messages.ErrorMessageH\x00R\x05error\x12>\n" +
	"\vcell_update\x18\a \x01(\v2\x1b.messages.CellUpdateMessageH\x00R\n" +
	"cellUpdateB\t\n" +
	"\amessage\"\xe6\x02\n" +
	"\rClientMessage\x12\x1c\n" +
	"\bnickname\x18\x01 \x01(\tH\x00R\bnickname\x121\n" +
	"\x06cursor\x18\x02 \x01(\v2\x17.messages.CursorMessageH\x00R\x06cursor\x12;\n" +
	"\n" +
	"cell_click\x18\x03 \x01(\v2\x1a.messages.CellClickMessageH\x00R\tcellClick\x12+\n" +
	"\x04hint\x18\x04 \x01(\v2\x15.messages.HintMessageH\x00R\x04hint\x125\n" +
	"\bnew_game\x18\x05 \x01(\v2\x18.messages.NewGameMessageH\x00R\anewGame\x12+\n" +
	"\x04chat\x18\x06 \x01(\v2\x15.messages.ChatMessageH\x00R\x04chat\x12+\n" +
	"\x04ping\x18\a \x01(\v2\x15.messages.PingMessageH\x00R\x04pingB\t\n" +
	"\amessage\"\x9f\x03\n" +
	"\x10GameStateMessage\x12%\n" +
	"\x05board\x18\x01 \x01(\v2\x0f.messages.BoardR\x05board\x12\x12\n" +
	"\x04rows\x18\x02 \x01(\x05R\x04rows\x12\x12\n" +
	"\x04cols\x18\x03 \x01(\x05R\x04cols\x12\x14\n" +
	"\x05mines\x18\x04 \x01(\x05R\x05mines\x12\x1b\n" +
	"\tgame_over\x18\x05 \x01(\bR\bgameOver\x12\x19\n" +
	"\bgame_won\x18\x06 \x01(\bR\agameWon\x12\x1a\n" +
	"\brevealed\x18\a \x01(\x05R\brevealed\x12\x1d\n" +
	"\n" +
	"hints_used\x18\b \x01(\x05R\thintsUsed\x121\n" +
	"\n" +
	"safe_cells\x18\t \x03(\v2\x12.messages.SafeCellR\tsafeCells\x121\n" +
	"\n" +
	"cell_hints\x18\n" +
	" \x03(\v2\x12.messages.CellHintR\tcellHints\x12&\n" +
	"\x0floser_player_id\x18\v \x01(\tR\rloserPlayerId\x12%\n" +
	"\x0eloser_nickname\x18\f \x01(\tR\rloserNickname\"*\n" +
	"\x05Board\x12!\n" +
	"\x04rows\x18\x01 \x03(\v2\r.messages.RowR\x04rows\"+\n" +
	"\x03Row\x12$\n" +
	"\x05cells\x18\x01 \x03(\v2\x0e.messages.CellR\x05cells\"\xa5\x01\n" +
	"\x04Cell\x12\x17\n" +
	"\ais_mine\x18\x01 \x01(\bR\x06isMine\x12\x1f\n" +
	"\vis_revealed\x18\x02 \x01(\bR\n" +
	"isRevealed\x12\x1d\n" +
	"\n" +
	"is_flagged\x18\x03 \x01(\bR\tisFlagged\x12%\n" +
	"\x0eneighbor_mines\x18\x04 \x01(\x05R\rneighborMines\x12\x1d\n" +
	"\n" +
	"flag_color\x18\x05 \x01(\tR\tflagColor\".\n" +
	"\bSafeCell\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\"B\n" +
	"\bCellHint\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xc9\x01\n" +
	"\vChatMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\x12\x1b\n" +
	"\tis_system\x18\x05 \x01(\bR\bisSystem\x12\x16\n" +
	"\x06action\x18\x06 \x01(\tR\x06action\x12\x10\n" +
	"\x03row\x18\a \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\b \x01(\x05R\x03col\"z\n" +
	"\rCursorMessage\x12\x1b\n" +
	"\tplayer_id\x18\x01 \x01(\tR\bplayerId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x12\f\n" +
	"\x01x\x18\x04 \x01(\x01R\x01x\x12\f\n" +
	"\x01y\x18\x05 \x01(\x01R\x01y\"<\n" +
	"\x0ePlayersMessage\x12*\n" +
	"\aplayers\x18\x01 \x03(\v2\x10.messages.PlayerR\aplayers\"J\n" +
	"\x06Player\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\"$\n" +
	"\fErrorMessage\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\r\n" +
	"\vPongMessage\"\r\n" +
	"\vPingMessage\"J\n" +
	"\x10CellClickMessage\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12\x12\n" +
	"\x04flag\x18\x03 \x01(\bR\x04flag\"1\n" +
	"\vHintMessage\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\"\x10\n" +
	"\x0eNewGameMessage\"\x85\x02\n" +
	"\x11CellUpdateMessage\x12\x1b\n" +
	"\tgame_over\x18\x01 \x01(\bR\bgameOver\x12\x19\n" +
	"\bgame_won\x18\x02 \x01(\bR\agameWon\x12\x1a\n" +
	"\brevealed\x18\x03 \x01(\x05R\brevealed\x12\x1d\n" +
	"\n" +
	"hints_used\x18\x04 \x01(\x05R\thintsUsed\x12&\n" +
	"\x0floser_player_id\x18\x05 \x01(\tR\rloserPlayerId\x12%\n" +
	"\x0eloser_nickname\x18\x06 \x01(\tR\rloserNickname\x12.\n" +
	"\aupdates\x18\a \x03(\v2\x14.messages.CellUpdateR\aupdates\"X\n" +
	"\n" +
	"CellUpdate\x12\x10\n" +
	"\x03row\x18\x01 \x01(\x05R\x03row\x12\x10\n" +
	"\x03col\x18\x02 \x01(\x05R\x03col\x12&\n" +
	"\x04type\x18\x03 \x01(\x0e2\x12.messages.CellTypeR\x04type*\xe0\x02\n" +
	"\bCellType\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_0\x10\x00\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_1\x10\x01\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_2\x10\x02\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_3\x10\x03\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_4\x10\x04\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_5\x10\x05\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_6\x10\x06\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_7\x10\a\x12\x18\n" +
	"\x14CELL_TYPE_NEIGHBOR_8\x10\b\x12\x12\n" +
	"\x0eCELL_TYPE_MINE\x10\t\x12\x12\n" +
	"\x0eCELL_TYPE_SAFE\x10\n" +
	"\x12\x15\n" +
	"\x11CELL_TYPE_UNKNOWN\x10\v\x12\x14\n" +
	"\x10CELL_TYPE_DANGER\x10\f\x12\x15\n" +
	"\x10CELL_TYPE_CLOSED\x10\xff\x01B\x19Z\x17minesweeperonline/protob\x06proto3"

var (
	file_messages_proto_rawDescOnce sync.Once
	file_messages_proto_rawDescData []byte
)

func file_messages_proto_rawDescGZIP() []byte {
	file_messages_proto_rawDescOnce.Do(func() {
		file_messages_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)))
	})
	return file_messages_proto_rawDescData
}

var file_messages_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_messages_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_messages_proto_goTypes = []any{
	(CellType)(0),             // 0: messages.CellType
	(*WebSocketMessage)(nil),  // 1: messages.WebSocketMessage
	(*ClientMessage)(nil),     // 2: messages.ClientMessage
	(*GameStateMessage)(nil),  // 3: messages.GameStateMessage
	(*Board)(nil),             // 4: messages.Board
	(*Row)(nil),               // 5: messages.Row
	(*Cell)(nil),              // 6: messages.Cell
	(*SafeCell)(nil),          // 7: messages.SafeCell
	(*CellHint)(nil),          // 8: messages.CellHint
	(*ChatMessage)(nil),       // 9: messages.ChatMessage
	(*CursorMessage)(nil),     // 10: messages.CursorMessage
	(*PlayersMessage)(nil),    // 11: messages.PlayersMessage
	(*Player)(nil),            // 12: messages.Player
	(*ErrorMessage)(nil),      // 13: messages.ErrorMessage
	(*PongMessage)(nil),       // 14: messages.PongMessage
	(*PingMessage)(nil),       // 15: messages.PingMessage
	(*CellClickMessage)(nil),  // 16: messages.CellClickMessage
	(*HintMessage)(nil),       // 17: messages.HintMessage
	(*NewGameMessage)(nil),    // 18: messages.NewGameMessage
	(*CellUpdateMessage)(nil), // 19: messages.CellUpdateMessage
	(*CellUpdate)(nil),        // 20: messages.CellUpdate
}
var file_messages_proto_depIdxs = []int32{
	3,  // 0: messages.WebSocketMessage.game_state:type_name -> messages.GameStateMessage
	9,  // 1: messages.WebSocketMessage.chat:type_name -> messages.ChatMessage
	10, // 2: messages.WebSocketMessage.cursor:type_name -> messages.CursorMessage
	11, // 3: messages.WebSocketMessage.players:type_name -> messages.PlayersMessage
	14, // 4: messages.WebSocketMessage.pong:type_name -> messages.PongMessage
	13, // 5: messages.WebSocketMessage.error:type_name -> messages.ErrorMessage
	19, // 6: messages.WebSocketMessage.cell_update:type_name -> messages.CellUpdateMessage
	10, // 7: messages.ClientMessage.cursor:type_name -> messages.CursorMessage
	16, // 8: messages.ClientMessage.cell_click:type_name -> messages.CellClickMessage
	17, // 9: messages.ClientMessage.hint:type_name -> messages.HintMessage
	18, // 10: messages.ClientMessage.new_game:type_name -> messages.NewGameMessage
	9,  // 11: messages.ClientMessage.chat:type_name -> messages.ChatMessage
	15, // 12: messages.ClientMessage.ping:type_name -> messages.PingMessage
	4,  // 13: messages.GameStateMessage.board:type_name -> messages.Board
	7,  // 14: messages.GameStateMessage.safe_cells:type_name -> messages.SafeCell
	8,  // 15: messages.GameStateMessage.cell_hints:type_name -> messages.CellHint
	5,  // 16: messages.Board.rows:type_name -> messages.Row
	6,  // 17: messages.Row.cells:type_name -> messages.Cell
	12, // 18: messages.PlayersMessage.players:type_name -> messages.Player
	20, // 19: messages.CellUpdateMessage.updates:type_name -> messages.CellUpdate
	0,  // 20: messages.CellUpdate.type:type_name -> messages.CellType
	21, // [21:21] is the sub-list for method output_type
	21, // [21:21] is the sub-list for method input_type
	21, // [21:21] is the sub-list for extension type_name
	21, // [21:21] is the sub-list for extension extendee
	0,  // [0:21] is the sub-list for field type_name
}

func init() { file_messages_proto_init() }
func file_messages_proto_init() {
	if File_messages_proto != nil {
		return
	}
	file_messages_proto_msgTypes[0].OneofWrappers = []any{
		(*WebSocketMessage_GameState)(nil),
		(*WebSocketMessage_Chat)(nil),
		(*WebSocketMessage_Cursor)(nil),
		(*WebSocketMessage_Players)(nil),
		(*WebSocketMessage_Pong)(nil),
		(*WebSocketMessage_Error)(nil),
		(*WebSocketMessage_CellUpdate)(nil),
	}
	file_messages_proto_msgTypes[1].OneofWrappers = []any{
		(*ClientMessage_Nickname)(nil),
		(*ClientMessage_Cursor)(nil),
		(*ClientMessage_CellClick)(nil),
		(*ClientMessage_Hint)(nil),
		(*ClientMessage_NewGame)(nil),
		(*ClientMessage_Chat)(nil),
		(*ClientMessage_Ping)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_messages_proto_rawDesc), len(file_messages_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_messages_proto_goTypes,
		DependencyIndexes: file_messages_proto_depIdxs,
		EnumInfos:         file_messages_proto_enumTypes,
		MessageInfos:      file_messages_proto_msgTypes,
	}.Build()
	File_messages_proto = out.File
	file_messages_proto_goTypes = nil
	file_messages_proto_depIdxs = nil
}
